image:
  file: .gitpod.Dockerfile

tasks:
  - init: dotnet restore && dotnet build --configuration Debug --no-restore
    command: dotnet watch -p ./malimo.Tests test
  - openMode: split-right
    command: mob status

vscode:
  extensions:
    - muhammad-sammy.csharp
