@startuml
left to right direction
set namespaceSeparator none

component "malimo" <<system>> as m {
  portin " " as cliPort
  portin " " as maintenancePort

  [Chocolatey] <<chocolatey package>> as choco
  [malimo.rb] <<homebrew cask>> as cask
  [malimo] <<application>> as malimo

}

() CLI as cli
cli -- cliPort
cliPort -- malimo
malimo -- "Filesystem"

() "Install, update, \nuninstall" as maintenance
maintenance -- maintenancePort
maintenancePort -- cask
maintenancePort -- choco
@enduml