name: Publish analysis results

on:
  workflow_call

jobs:
  test:
    name: Publish analysis results
    runs-on: ubuntu-latest
    
    steps:
      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: coverage-reports
          path: coverage-reports

      - name: Publish coverage report to CodeClimate
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: coverage-reports/lcov.info:lcov
