name: Run unit tests

on:
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        description: "CodeClimate Test Coverage ID"
        required: true

jobs:
  test:
    name: Publish coverage report to CodeClimate
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: coverage-reports
          path: report

      - name: Publish coverage report to CodeClimate
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: report/lcov.info:lcov
