name: Publish to CodeClimate

on:
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        description: "CodeClimate Test Coverage ID"
        required: true

jobs:
  test:
    name: Publish to CodeClimate
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Download build result
        uses: actions/download-artifact@v3
        with:
          name: build-result
          path: malimo/obj/Release/net7.0

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: coverage-reports
          path: report

      - name: Publish coverage report to CodeClimate
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: report/lcov.info:lcov
