name: .NET

# Save energy - only build main branch updates
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  RETENTION_DAYS: 5

jobs:
  determine_version:
    uses: ./.github/workflows/_determine_version.yml

  test:
    uses: ./.github/workflows/_unit_tests.yml

  publish_macos:
    name: Publish macOS
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [determine_version, test]
    
    uses: ./.github/workflows/_publish_macos.yml
    with:
      assembly_version: ${{ needs.determine_version.outputs.assembly_version }}
      use_notarize: true
    secrets: inherit

  publish_win:
    name: Publish Windows
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [determine_version, test]
    
    uses: ./.github/workflows/_publish_win.yml
    with:
      semantic_version: ${{ needs.determine_version.outputs.semantic_version }}
      assembly_version: ${{ needs.determine_version.outputs.assembly_version }}
    
  release:
    name: Release
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [determine_version, test, publish_macos, publish_win]
    
    runs-on: windows-latest
    
    defaults:
      run:
        shell: bash
    
    # Configure GITHUB_TOKEN so that it allows uploading to the release
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
    
      - uses: actions/download-artifact@v3
        
      - name: Create release folder
        run: mkdir release
        
      - name: Move ZIPs to release folder
        run: |
          mv -v malimo.osx.12-arm64.bottle.zip/malimo.osx.12-arm64.bottle.zip ./release/  
          mv -v malimo.osx.12-x64.bottle.zip/malimo.osx.12-x64.bottle.zip ./release/
          mv -v malimo.win-x64.zip/malimo.win-x64.zip ./release/
          mv -v malimo.${{ needs.determine_version.outputs.semantic_version }}.nupkg/malimo.${{ needs.determine_version.outputs.semantic_version }}.nupkg ./release/

      # Adopted from https://github.com/svenstaro/upload-release-action
      - name: Read CHANGELOG.md and use it as a body of new release
        id: read_release
        run: |
          r=$(cat CHANGELOG.md)                             # <--- Read CHANGELOG.md
          r="${r//'%'/%25}"                                 # Multiline escape sequences for %
          r="${r//$'\n'/%0A}"                               # Multiline escape sequences for '\n'
          r="${r//$'\r'/%0D}"                               # Multiline escape sequences for '\r'
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT          # <--- Set environment variable

      - name: Upload applications to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: release/*
          tag: ${{ github.ref }}
          overwrite: true
          body: ${{ steps.read_release.outputs.RELEASE_BODY }}

      - name: Push Chocolatey package
        run: |
          choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
          choco push ./release/malimo.${{ needs.determine_version.outputs.semantic_version }}.nupkg --source https://push.chocolatey.org/
