name: .NET

# Save energy - only build main branch updates
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  PUBLISH_PATH: publish

jobs:
  build-and-test:
    runs-on: macos-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dotnet global tools (coverlet, reportgenerator)
        run: |
          dotnet tool install --global coverlet.console
          dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='./TestResults/coverage.cobertura.xml'

      - name: Generate coverage reports
        run: reportgenerator "-reports:MarkdownLinkedImagesMover.Tests/TestResults/*.xml" \
          "-targetdir:report" \
          "-reporttypes:Html;lcov" \
          "-title:DotnetStarter"

      - name: Attach coverage reports to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: report

  publish:
    runs-on: macos-latest
    name: Publish
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    
    needs: build-and-test
    
    # Allow publishing to the release
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Create publish package
        run: |
          dotnet publish MarkdownLinkedImagesMover/MarkdownLinkedImagesMover.csproj --configuration Release --runtime osx.12-arm64 --self-contained true --output markdown-linked-images-mover
          rm markdown-linked-images-mover/*.pdb
          chmod +x markdown-linked-images-mover/MarkdownLinkedImagesMover

      - name: Add cert to keychain
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_ID_APP_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_ID_APP_CERTIFICATE_PASSWORD }}

      - name: Sign publish artifacts
        run: |
          /bin/sh BuildAndReleaseScripts/SignMac.sh "markdown-linked-images-mover/MarkdownLinkedImagesMover" "markdown-linked-images-mover" "Developer ID Application: Stefan Boos" "BuildAndReleaseScripts/entitlements.plist"

      - name: Zip publish artifacts
        run: |
          ditto -c --sequesterRsrc -k -V markdown-linked-images-mover markdown-linked-images-mover.zip

      - name: Notarize publish artifacts
        run: |
          /bin/sh BuildAndReleaseScripts/Notarize.sh "xpdbumm@boos.systems" "${{ secrets.APPLE_ID_APP_SPECIFIC_PASSWORD }}" "M9YN683HBZ" "./markdown-linked-images-mover.zip"

      - name: Attach notarize log to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: notarize_log.json
          path: ./notarize_log.json

      # Adopted from https://github.com/svenstaro/upload-release-action
      - name: Read CHANGELOG.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat CHANGELOG.md)                             # <--- Read CHANGELOG.md
          r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT          # <--- Set environment variable

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: markdown-linked-images-mover.zip
          asset_name: markdown-linked-images-mover.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: ${{ steps.read_release.outputs.RELEASE_BODY }}
