name: .NET

# Save energy - only build main branch updates
on:
  push:
    branches:
      - main
      - ci/publish
  pull_request:
    branches:
      - main

env:
  PUBLISH_PATH: publish

jobs:
  build-and-test:
    runs-on: macos-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dotnet global tools (coverlet, reportgenerator)
        run: |
          dotnet tool install --global coverlet.console
          dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='./TestResults/coverage.cobertura.xml'

      - name: Generate coverage reports
        run: reportgenerator "-reports:MarkdownLinkedImagesMover.Tests/TestResults/*.xml" \
          "-targetdir:report" \
          "-reporttypes:Html;lcov" \
          "-title:DotnetStarter"

      - name: Attach coverage reports to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: report

      - name: Create publish dir
        run: |
          dotnet publish MarkdownLinkedImagesMover/MarkdownLinkedImagesMover.csproj --configuration Release --runtime osx.12-arm64 --self-contained true --output markdown-linked-images-mover
          rm markdown-linked-images-mover/*.pdb
          chmod +x markdown-linked-images-mover/MarkdownLinkedImagesMover

      - name: Add Cert to Keychain
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_ID_APP_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_ID_APP_CERTIFICATE_PASSWORD }}

      - name: Sign publish artifacts
        run: |
          /bin/sh BuildAndReleaseScripts/SignMac.sh "markdown-linked-images-mover/MarkdownLinkedImagesMover" "markdown-linked-images-mover/*" "Developer ID Application: Stefan Boos" "BuildAndReleaseScripts/entitlements.plist"

      - name: Zip publish artifacts
        run: |
          zip -r markdown-linked-images-mover.zip markdown-linked-images-mover/*

      - name: Notarize application
        run: |
          /bin/sh BuildAndReleaseScripts/Notarize.sh "xpdbumm@boos.systems" "${{ secrets.APPLE_ID_APP_SPECIFIC_PASSWORD }}" "systems.boos.markdown-linked-images-mover" "M9YN683HBZ" "./markdown-linked-images-mover.zip"

      - name: Attach application zip to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: markdown-linked-images-mover
          path: ./markdown-linked-images-mover
