name: .NET

# Save energy - only build main branch updates
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  RETENTION_DAYS: 5

jobs:
  determine_version:
    uses: ./.github/workflows/_determine_version.yml

  test:
    uses: ./.github/workflows/_unit_tests.yml

  publish_macos:
    name: Publish macOS
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [determine_version, test]
    
    uses: ./.github/workflows/_publish_macos.yml
    with:
      assembly_version: ${{ needs.determine_version.outputs.assembly_version }}
      use_notarize: true
    secrets: inherit

  publish_win:
    name: Publish Windows
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [determine_version, test]
    
    uses: ./.github/workflows/_publish_win.yml
    with:
      semantic_version: ${{ needs.determine_version.outputs.semantic_version }}
      assembly_version: ${{ needs.determine_version.outputs.assembly_version }}
    
  release:
    name: Release
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [determine_version, test, publish_macos, publish_win]

    uses: ./.github/workflows/_publish_win.yml
    with:
      semantic_version: ${{ needs.determine_version.outputs.semantic_version }}
      is_dry_run: false
    secrets: inherit
