name: .NET

# Save energy - only build main branch updates
on:
  push:
    branches:
      - main
      - ci/publish
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dotnet global tools (coverlet, reportgenerator)
        run: |
          dotnet tool install --global coverlet.console
          dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='./TestResults/coverage.cobertura.xml'

      - name: Generate coverage reports
        run: reportgenerator "-reports:MarkdownLinkedImagesMover.Tests/TestResults/*.xml" \
          "-targetdir:report" \
          "-reporttypes:Html;lcov" \
          "-title:DotnetStarter"

      - name: Attach coverage reports to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: report

      - name: Package
        run: dotnet publish MarkdownLinkedImagesMover/MarkdownLinkedImagesMover.csproj --configuration Release --runtime osx.12-arm64 --self-contained true

      - name: Attach package to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: markdown-linked-images-mover
          path: MarkdownLinkedImagesMover/bin/Release/net7.0/osx.12-arm64/publish
