name: .NET (manual)

on: workflow_dispatch

env:
  RETENTION_DAYS: 1

jobs:
  determine_version:
    uses: ./.github/workflows/_determine_version.yml

  test:
    uses: ./.github/workflows/_unit_tests.yml

  publish_macos:
    name: Publish macOS
    needs: [determine_version, test]
    
    uses: ./.github/workflows/_publish_macos.yml
    with:
      assembly_version: ${{ needs.determine_version.outputs.assembly_version }}
      use_notarize: false
    secrets: inherit

  publish_win:
    name: Publish Windows
    needs: [determine_version, test]
    
    uses: ./.github/workflows/_publish_win.yml
    with:
      semantic_version: ${{ needs.determine_version.outputs.semantic_version }}
      assembly_version: ${{ needs.determine_version.outputs.assembly_version }}

  release:
    name: Release
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [determine_version, test, publish_macos, publish_win]

    uses: ./.github/workflows/_publish_win.yml
    with:
      semantic_version: ${{ needs.determine_version.outputs.semantic_version }}
      is_dry_run: true
    secrets: inherit
