name: .NET (manual)

on: workflow_dispatch

env:
  RETENTION_DAYS: 1

jobs:
  determine_version:
    uses: ./.github/workflows/_determine_version.yml

  test:
    uses: ./.github/workflows/_unit_tests.yml
    with:
      retention_days: 1

  publish_macos:
    name: Publish macOS
    needs: [determine_version, test]
    
    uses: ./.github/workflows/_publish_macos.yml
    with:
      assembly_version: ${{ needs.determine_version.outputs.assembly_version }}
      use_notarize: false
    secrets: inherit

  publish_win:
    name: Publish Windows
    needs: [determine_version, test]
    
    strategy:
      matrix:
        runtime:
          - win-x64
    
    env:
      PUBLISH_DIR: malimo.${{ matrix.runtime }}
      PUBLISH_ZIP_FILENAME: malimo.${{ matrix.runtime }}.zip

    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Create application
        run: |
          dotnet publish malimo/malimo.csproj --configuration Release --runtime "${{ matrix.runtime }}" --self-contained true -p:PublishSingleFile=true -p:Version=${{ needs.determine_version.outputs.assembly_version }} --output "${{ env.PUBLISH_DIR }}"

      - name: ZIP application
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: ${{ env.PUBLISH_DIR }}
          filename: ${{ env.PUBLISH_ZIP_FILENAME }}
          exclusions: '*.pdb'

      - name: Attach application to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PUBLISH_ZIP_FILENAME }}
          path: ${{ env.PUBLISH_ZIP_FILENAME }}
          retention-days: ${{ env.RETENTION_DAYS }}

      - name: Prepare Chocolatey configuration
        run: pwsh ./build/ReplaceVariablesInChocolateyConfiguration.ps1 -version ${{ needs.determine_version.outputs.semantic_version }} -zipFile ${{ env.PUBLISH_ZIP_FILENAME }}

      - name: Create Chocolatey package
        run: choco pack ./chocolatey/malimo.nuspec

      - name: Attach Chocolatey package to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: malimo.${{ needs.determine_version.outputs.semantic_version }}.nupkg
          path: malimo.${{ needs.determine_version.outputs.semantic_version }}.nupkg
          retention-days: ${{ env.RETENTION_DAYS }}
  