name: .NET

# Save energy - only build main branch updates
on:
  push:

env:
  RETENTION_DAYS: 1
  VERSION_FROM_TAG: x0.1.0-snapshot 

jobs:
  publish-win:
    name: Publish Windows
    defaults:
      run:
        shell: bash
    
    strategy:
      matrix:
        runtime:
          - win-x64
    
    env:
      PUBLISH_DIR: malimo.${{ matrix.runtime }}
      PUBLISH_ZIP_FILENAME: malimo.${{ matrix.runtime }}.zip

    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Get version from tag
        if: ${{ startsWith(github.ref, 'refs/tags/x') }}
        run: echo "VERSION_FROM_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Determine semantic version
        run: echo "SEMANTIC_VERSION=${VERSION_FROM_TAG#x}" >> $GITHUB_ENV
          
      - name: Determine version for .NET assemblies
        run: echo "DOTNET_PUBLISH_VERSION=${SEMANTIC_VERSION%%-*}.0" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Create application
        run: |
          dotnet publish malimo/malimo.csproj --configuration Release --runtime "${{ matrix.runtime }}" --self-contained true -p:PublishSingleFile=true -p:Version=${{ env.DOTNET_PUBLISH_VERSION }} --output "${{ env.PUBLISH_DIR }}"

      - name: ZIP application
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: ${{ env.PUBLISH_DIR }}
          filename: ${{ env.PUBLISH_ZIP_FILENAME }}
          exclusions: '*.pdb'

      - name: Attach application to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PUBLISH_ZIP_FILENAME }}
          path: ${{ env.PUBLISH_ZIP_FILENAME }}
          retention-days: ${{ env.RETENTION_DAYS }}

      - name: Prepare Chocolatey configuration
        run: pwsh ./BuildAndReleaseScripts/ReplaceVariablesInChocolateyConfiguration.ps1 -version ${{ env.SEMANTIC_VERSION }} -zipFile malimo.win-x64.zip

      - name: Create Chocolatey package
        run: choco pack --outputdirectory . ./Chocolatey/malimo.nuspec

      - name: Attach Chocolatey package to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: malimo.0.1.7-alpha.nupkg
          path: malimo.0.1.7-alpha.nupkg
          retention-days: ${{ env.RETENTION_DAYS }}

